{
 "title": "Moleculer Prometheus demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "moleculer_nodes_total" }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "moleculer_services_total" }
   ]
  },
  {
   "title": "Actions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "moleculer_actions_total" }
   ]
  },
  {
   "title": "Events",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "moleculer_events_total" }
   ]
  },
  {
   "title": "Total calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    { "expr": "sum(moleculer_req_total)" }
   ]
  },
  {
   "title": "Total errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(moleculer_req_errors_total)"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(irate(moleculer_req_duration_ms_sum[1m]))"
    }
   ]
  },
  {
   "title": "Rps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_total[1m]))"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(moleculer_req_total[1m]))",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(irate(moleculer_req_errors_total[1m]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Available nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "moleculer_nodes_total" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 } },
  {
   "title": "Error types",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (errorName) (irate(moleculer_req_errors_total[1m]))",
     "legendFormat": "{{errorName}}"
    }
   ]
  }
 ]
}